config/routes.rb
Rails.application.routes.draw do
  root 'logins#new'
  
  get '/home', to: 'logins#new'
  
  resources :enrollments
  
  resources :clients, except: [:new]
  
  get '/register', to: 'clients#new'
  
  get '/login', to: 'logins#new'
  
  post '/login', to: 'logins#create'
  
  get '/logout', to: 'logins#destroy'
  
  resources :references, only: [:new, :create, :show]
  resources :preferences, only: [:new, :create, :show]
  resources :bodies, only: [:new, :create, :show]
  resources :healths, only: [:new, :create, :show]
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :enrollments
  before_save { self.email = email.downcase }
  validates :clientname, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @clients = Client.paginate(page: params[:page], per_page: 3)
  end

  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    if @client.save
      #do something
      flash[:success] = "Your account has been created successfully"
      session[:client_id] = @client.id
      redirect_to new_enrollment_path
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @client.update(client_params)
      flash[:success] = "Your profile has been updated successfully"
      redirect_to client_path(@client) #TODO change to show client page
    else
      render 'edit'
    end
  end
  
  def show
   
    @enrollments = @client.enrollments.paginate(page: params[:page], per_page: 3)
  end
  
  private
  
    def client_params
      params.require(:client).permit(:clientname, :email, :password)
    end
    
    def set_client
      @client = Client.find(params[:id])
    end
    
    def require_same_user
      if current_user != @client
      flash[:danger] = "You can only edit your own profile"
      redirect_to root_path
      end
    end
      
end

app/views/clients/_form.html.erb
<%= render 'shared/errors', obj: @client %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @client do |f| %>
      <%= f.label "User Name" %>
      <%= f.text_field :clientname %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.submit(@client.new_record? ? 'Register' : 'Edit profile', class: "btn btn-success") %>
      
    <% end %>
  </div>
</div><br><br><br><br><br><br>

app/views/clients/edit.html.erb
<%= render 'shared/page_title', title: "Edit your Profile" %>

<%= render 'form' %>

app/views/clients/index.html.erb
<%= render 'shared/page_title', title: "All Clients" %>

<ul class="nav nav-tabs">
  <li>
    <%= link_to "Enrollments", enrollments_path %>
  </li>
  <li class="active">
    <%= link_to "Clients", clients_path %>
  </li>
</ul>
<br/><br/>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
    
  </div>
</div>

<% @clients.each do |client| %>
  <div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%=link_to gravatar_for(client, size: 200), client_path(client) %>
    <p>
      <h5>Client name: <%= client.clientname %></h5>
    </p>
  </div>
</div>
<% end %>
<br/><br/><br/>

app/views/clients/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>

<%= render 'form' %>

app/views/clients/show.html.erb
<%= render 'shared/page_title', title: "Client: " + @client.clientname %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @client, size: 200 %>
    <hr/>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3><em>Massage Enrollments:</em></h3>
    <%= will_paginate @enrollments %>
  </div>
</div>

<% @enrollments.each do |enrollment| %> 
  <div class="col-lg-6 well col-lg-offset-3">
    <h4><%= link_to enrollment.name, enrollment_path(enrollment) %></h4>
    <p><%= enrollment.address %></p>
    <p><%= enrollment.telephone %></p>
    
    <p></p>
    
    <p>
      
      <span class='quiet'><small> Updated: <%= time_ago_in_words(enrollment.updated_at) %> ago</small></span>
    </p>
    
  </div><br/><br/><br/>
<% end %>