config/routes.rb
Rails.application.routes.draw do
  root 'logins#new'
  
  get '/home', to: 'logins#new'
  
  resources :enrollments
  
  resources :clients, except: [:new]
  
  get '/register', to: 'clients#new'
  
  get '/login', to: 'logins#new'
  
  post '/login', to: 'logins#create'
  
  get '/logout', to: 'logins#destroy'
  
  resources :references, only: [:new, :create, :show]
  resources :preferences, only: [:new, :create, :show]
  resources :bodies, only: [:new, :create, :show]
  resources :healths, only: [:new, :create, :show]
  
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_preferences
  has_many :enrollments, through: :enrollment_preferences
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  
  def show
    @preference = Preference.find(params[:id])
    @enrollments = @preference.enrollments.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @preference = Preference.new
  end
  
  def create
    @preference = Preference.new(preference_params)
    if @preference.save
      flash[:success] = "Preferences was created succesfully"
      redirect_to enrollments_path
    else
      render 'new'
    end
    
  end
  
  private
  
  def preference_params
    params.require(:preference).permit(:name)
  end
end

app/views/preferences/_preference.html.erb
<span class='quiet'><%= link_to preference.name, preference_path(preference)  %> | </span>

app/views/preferences/new.html.erb
<%= render 'shared/page_title', title: "Create new preferences" %>

<%= render 'shared/errors', obj: @preference %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @preference do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.submit 'Create preference', class: "btn btn-success" %>
      
    <% end %> 
  </div>
</div>

app/views/preferences/show.html.erb
<%= render 'shared/page_title', title: "Enrollments for: " + @preference.name %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Enrollments", enrollments_path %>
  </li>
  <li>
    <%= link_to "Clients", clients_path %>
  </li>
</ul>

<%= will_paginate @enrollments %>

<% @preference.enrollments.each do |enrollment| %>
  <div class="row">
    
    <div class="col-md-4">
      <section class="client_info center">
        <%= link_to gravatar_for(enrollment.client, size: 100), client_path(enrollment.client) %>
        <h5>Client name: <%= enrollment.client.clientname %></h5>
      </section>
    </div>
    

    <div class="col-lg-4 well">
      <h4><%= link_to enrollment.name, enrollment_path(enrollment) %></h4>
      
      <p><%= enrollment.address %></p>
      <p><%= enrollment.suburb %></p>
      <p>Preference: <%= render enrollment.preferences %></p>
      <p>Reference: <%= render enrollment.references %></p>
      
      <p>
        <span class='quiet'><small> Created: <%= time_ago_in_words(enrollment.created_at) %> ago, </small></span>
        <span class='quiet'><small> Updated: <%= time_ago_in_words(enrollment.updated_at) %> ago</small></span>
      </p>

    </div>
  </div>
  <hr/>
<% end %>

<%= will_paginate @enrollments %>
<br><br><br><br/><br/>