config/routes.rb
Rails.application.routes.draw do
  root 'logins#new'
  
  get '/home', to: 'logins#new'
  
  resources :enrollments
  
  resources :clients, except: [:new]
  
  get '/register', to: 'clients#new'
  
  get '/login', to: 'logins#new'
  
  post '/login', to: 'logins#create'
  
  get '/logout', to: 'logins#destroy'
  
  resources :references, only: [:new, :create, :show]
  resources :preferences, only: [:new, :create, :show]
  resources :bodies, only: [:new, :create, :show]
  resources :healths, only: [:new, :create, :show]
  
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_references
  has_many :enrollments, through: :enrollment_references
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  
  def show
    @reference = Reference.find(params[:id])
    @enrollments = @reference.enrollments.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @reference = Reference.new
  end

  def create
    @reference = Reference.new(reference_params)
    if @reference.save
      flash[:success] = "Reference was created successfully"
      redirect_to enrollments_path
    else
       
    render 'new'
    end
  end
  
  
  private
  
  def reference_params
    params.require(:reference).permit(:name)
  end
end

app/views/references/_reference.html.erb
<span class='quiet'><%= link_to reference.name, reference_path(reference) %> | </span>

app/views/references/new.html.erb
<%= render 'shared/page_title', title: "Create new references" %>

<%= render 'shared/errors', obj: @reference %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @reference do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.submit 'Create reference', class: "btn btn-success" %>
      
    <% end %> 
  </div>
</div>

app/views/references/show.html.erb
<%= render 'shared/page_title', title: "Enrollments for: " + @reference.name %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Enrollments", enrollments_path %>
  </li>
  <li>
    <%= link_to "Clients", clients_path %>
  </li>
</ul>

<%= will_paginate @enrollments %>

<% @reference.enrollments.each do |enrollment| %>
  <div class="row">
    
    <div class="col-md-4">
      <section class="client_info center">
        <%= link_to gravatar_for(enrollment.client, size: 100), client_path(enrollment.client) %>
        <h5>Client name: <%= enrollment.client.clientname %></h5>
      </section>
    </div>
    

    <div class="col-lg-4 well">
      <h4><%= link_to enrollment.name, enrollment_path(enrollment) %></h4>
      
      <p><%= enrollment.address %></p>
      <p><%= enrollment.suburb %></p>
      <p>Preference: <%= render enrollment.preferences %></p>
      <p>Reference: <%= render enrollment.references %></p>
      
      <p>
        <span class='quiet'><small> Created: <%= time_ago_in_words(enrollment.created_at) %> ago, </small></span>
        <span class='quiet'><small> Updated: <%= time_ago_in_words(enrollment.updated_at) %> ago</small></span>
      </p>

    </div>
  </div>
  <hr/>
<% end %>

<%= will_paginate @enrollments %>
<br><br><br><br/><br/>