config/routes.rb
Rails.application.routes.draw do
  root 'logins#new'
  
  get '/home', to: 'logins#new'
  
  resources :enrollments
  
  resources :clients, except: [:new]
  
  get '/register', to: 'clients#new'
  
  get '/login', to: 'logins#new'
  
  post '/login', to: 'logins#create'
  
  get '/logout', to: 'logins#destroy'
  
  resources :references, only: [:new, :create, :show]
  resources :preferences, only: [:new, :create, :show]
  resources :bodies, only: [:new, :create, :show]
  resources :healths, only: [:new, :create, :show]
  
end

app/models/body.rb
class Body < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_bodies
  has_many :enrollments, through: :enrollment_bodies
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :enrollments
  before_save { self.email = email.downcase }
  validates :clientname, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :client #HARUS DIILANGIN
  has_many :enrollment_references
  has_many :references, through: :enrollment_references
  has_many :enrollment_preferences
  has_many :preferences, through: :enrollment_preferences
  has_many :enrollment_bodies
  has_many :bodies, through: :enrollment_bodies
  has_many :enrollment_healths
  has_many :healths, through: :enrollment_healths
  validates :client_id, presence: true #HARUS DIILANGIN
  validates :name, :address, :suburb, presence: true, length: { maximum: 100 }
  validates :dob, :post_code, presence: true
  validates :telephone, format: { with: /\d[0-9]\)*\z/, message: "bad format, please use accepted Australian format, ex: 0421813629" }
  default_scope -> { order(updated_at: :desc) }
end

app/models/enrollment_body.rb
class EnrollmentBody < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :body
  
end

app/models/enrollment_health.rb
class EnrollmentHealth < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :health
end

app/models/enrollment_preference.rb
class EnrollmentPreference < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :preference
end

app/models/enrollment_reference.rb
class EnrollmentReference < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :reference
  
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_many :enrollment_friends
  has_many :enrollments, through: :enrollment_references
end

app/models/health.rb
class Health < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_healths
  has_many :enrollments, through: :enrollment_healths
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_preferences
  has_many :enrollments, through: :enrollment_preferences
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :enrollment_references
  has_many :enrollments, through: :enrollment_references
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  validates :name, length: { minimum: 2, maximum: 25 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Client.find(session[:client_id]) if session[:client_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to client_path(current_user)
    end
  end
  
  def require_same_user
    if !logged_in?
      flash[:danger] = "You can only edit your own recipes"
      redirect_to client_path(current_user)
    end
  end
  
  def authorize_admin
    if !current_user.admin
      flash[:danger] = "I am sorry only admin can view this page"
      redirect_to client_path(current_user)
    end
  end

end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  def new
    @body = Body.new 
  end
  
  def create
    @body = Body.new(body_params)
    if @body.save
      flash[:success] = 'Skip body area was created succesfully'
      redirect_to enrollments_path
    else
      render 'new'
    end
  end
  
  private
  
  def body_params
    params.require(:body).permit(:name)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @clients = Client.paginate(page: params[:page], per_page: 3)
  end

  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    if @client.save
      #do something
      flash[:success] = "Your account has been created successfully"
      session[:client_id] = @client.id
      redirect_to new_enrollment_path
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @client.update(client_params)
      flash[:success] = "Your profile has been updated successfully"
      redirect_to client_path(@client) #TODO change to show client page
    else
      render 'edit'
    end
  end
  
  def show
   
    @enrollments = @client.enrollments.paginate(page: params[:page], per_page: 3)
  end
  
  private
  
    def client_params
      params.require(:client).permit(:clientname, :email, :password)
    end
    
    def set_client
      @client = Client.find(params[:id])
    end
    
    def require_same_user
      if current_user != @client
      flash[:danger] = "You can only edit your own profile"
      redirect_to root_path
      end
    end
      
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  def new
    @health = Health.new
  end
  
  def create 
    @health = Health.new(health_params)
    if @health.save
      flash[:success] = "Health condition info was created successfully"
      redirect_to enrollments_path
    else
      render 'new'
    end
  end
  
  private
  
  def health_params
    params.require(:health).permit(:name)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    
  end
  
  def create
    client = Client.find_by(email: params[:email])
    if client && client.authenticate(params[:password])
      session[:client_id] = client.id
      flash[:success] = "You are logged in"
      redirect_to enrollments_path
    else
      flash.now[:danger] = "Your email address or password does not match"
      render 'new'
    end
    
    
  end
  
  def destroy
    session[:client_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to enrollments_path if logged_in?
    
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  
  def show
    @reference = Reference.find(params[:id])
    @enrollments = @reference.enrollments.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @reference = Reference.new
  end

  def create
    @reference = Reference.new(reference_params)
    if @reference.save
      flash[:success] = "Reference was created successfully"
      redirect_to enrollments_path
    else
       
    render 'new'
    end
  end
  
  
  private
  
  def reference_params
    params.require(:reference).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def gravatar_for(client, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(client.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: client.clientname, class: "gravatar")
    
  end
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p class="navbar-text pull-left"> Stable Massage - Australia © 2016 - 
         <a href="http://stablemassage.com.au" target="_blank" >www.stablemassage.com.au</a>
    </p>
    
    <a href="http://youtube.com" class="navbar-btn btn-danger btn pull-right">
    <span class="glyphicon glyphicon-star"></span> - see our clinics on YouTube</a>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header>
    <nav class="navbar navbar-fixed-top navbar-default">
    
      <div class="nav-item">
              <%= link_to image_tag('stablelogosmall1.png'), root_path, id: "logo"  %>
      </div>
    
      <div class="container-fluid">
        <!-- BRAND AND TOGGLE GET GROUPED FOR BETTER MOBILE DISPLAY -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-collapse-1" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            
        </div><!-- NAVBAR HEADER -->
        
        
        <!-- COLLECT THE LINKS FORMS AND OTHER CONTENT FOR TOGGLING -->
        <div class="collapse navbar-collapse" id="bs-example-collapse-1">
            
              <ul class="nav navbar-nav navbar-left">
              
                
                <li><%= link_to "Home", root_path %></li>
                <% if !logged_in? %>
                  <li><%= link_to "New Client Form", register_path %></li>
                <% end %>
                <% if logged_in? %>
                  <li><%= link_to "Client New Form", new_enrollment_path %></li>
                  
                  <li class="dropdown">
                    <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
                      <%= current_user.clientname %> <b class="caret"></b>
                      <ul class="dropdown-menu">
                        <li><%= link_to "View Profile", client_path(current_user) %></li>
                        <li><%= link_to "Edit Profile", edit_client_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Logout", logout_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Enrollments", enrollments_path %></li>
                      </ul>
                    <% end %>
                  </li>
                <% else %>
                  <li><%= link_to "Admin Log in", login_path %></li>
                <% end %>
              
              </ul>
              
              <form class="navbar-form pull-right col-sm-4">
                    <div class="input-group">
                        <input type="search" class="form-control" placeholder="Search"/>
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">Search</button>
                        </span> 
                    </div>
              </form>
              
  
        </div><!-- /.navbar-collapse -->
        
      </div><!-- CONTAINER FLUID -->
      
    </nav><!-- NAVBAR --> 
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  
  <h1>Welcome to Stable Massage</h1>
  
  <h2>Best Massage Service in Melbourne</h2>
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
    
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5><strong>Please correct the following errors:</strong></h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>